# tasks file
---
- name: install dependencies
  ansible.builtin.apt:
    name: "{{ gnu_parallel_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - gnu-parallel
    - gnu-parallel-install
    - gnu-parallel-install-dependencies

- name: remove (distro version)
  ansible.builtin.apt:
    name: parallel
    state: absent
    purge: true
  when: gnu_parallel_remove_distro_version | bool
  tags:
    - configuration
    - gnu-parallel
    - gnu-parallel-remove
    - gnu-parallel-remove-distro

- name: create (download) directory
  ansible.builtin.file:
    path: "{{ gnu_parallel_download_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - gnu-parallel
    - gnu-parallel-install
    - gnu-parallel-install-download

- name: download (latest)
  ansible.builtin.get_url:
    url: "{{ gnu_parallel_download_url }}"
    dest: "{{ gnu_parallel_download_path }}/{{ gnu_parallel_download_url | basename }}"
    owner: root
    group: root
    mode: 0644
    force: true
  tags:
    - configuration
    - gnu-parallel
    - gnu-parallel-install
    - gnu-parallel-install-download

- name: create (build) directory
  ansible.builtin.file:
    path: "{{ gnu_parallel_build_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - gnu-parallel
    - gnu-parallel-install
    - gnu-parallel-install-build

- name: version check  # noqa risky-shell-pipe
  ansible.builtin.shell: >
    tar -jtf {{ gnu_parallel_download_path }}/{{ gnu_parallel_download_url | basename }} | head -n 1
  args:
    warn: false
  changed_when: false
  register: _version_check
  tags:
    - configuration
    - gnu-parallel
    - gnu-parallel-install
    - gnu-parallel-install-build

- name: extract
  ansible.builtin.unarchive:
    src: "{{ gnu_parallel_download_path }}/{{ gnu_parallel_download_url | basename }}"
    dest: "{{ gnu_parallel_build_path }}"
    creates: "{{ gnu_parallel_build_path }}/{{ _version_check.stdout }}"
    copy: false
  register: _unarchive
  tags:
    - configuration
    - gnu-parallel
    - gnu-parallel-install
    - gnu-parallel-install-build

- name: install  # noqa no-handler
  when: _unarchive is changed
  tags:
    - configuration
    - gnu-parallel
    - gnu-parallel-install
    - gnu-parallel-install-build
  block:

    - name: configure
      ansible.builtin.command: >
        ./configure
      args:
        chdir: "{{ gnu_parallel_build_path }}/{{ _version_check.stdout }}"
      changed_when: true
      tags:
        - gnu-parallel-install-build-configure

    - name: make
      ansible.builtin.command: >
        make -j{{ ansible_processor_cores + 1 }}
      args:
        chdir: "{{ gnu_parallel_build_path }}/{{ _version_check.stdout }}"
      changed_when: true
      tags:
        - gnu-parallel-install-build-make

    - name: make install
      ansible.builtin.command: >
        make install
      args:
        chdir: "{{ gnu_parallel_build_path }}/{{ _version_check.stdout }}"
      changed_when: true
      tags:
        - gnu-parallel-install-build-make-install

- name: silence citation notice
  ansible.builtin.copy:
    src: root/.parallel
    dest: "{{ ansible_env.HOME }}/"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
  tags:
    - configuration
    - gnu-parallel
    - gnu-parallel-silence-citation-notice

- name: verify
  ansible.builtin.command: >
    parallel --version
  changed_when: false
  tags:
    - configuration
    - gnu-parallel
    - gnu-parallel-install
    - gnu-parallel-install-verify
